name: gETH midrate daily

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"   # JST 09:00（必要なら変更）
  workflow_dispatch:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Run logger (single shot)
        run: node index.mjs --interval 0 --out data/geth_mid.csv
        env:
          BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}

      - name: Append to monthly CSV
        run: |
          set -e
          month=$(date -u +"%Y-%m")
          mkdir -p data
          if [ ! -f "data/geth_mid_${month}.csv" ]; then
            cp data/geth_mid.csv "data/geth_mid_${month}.csv"
          else
            tail -n +2 data/geth_mid.csv >> "data/geth_mid_${month}.csv"
          fi

      - name: Commit monthly CSV
        run: |
          set -e
          BRANCH="${GITHUB_REF_NAME:-main}"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git switch "$BRANCH" || git checkout -B "$BRANCH"
          git pull --rebase origin "$BRANCH" || true
          git add data/geth_mid_*.csv
          git commit -m "append: $(date -u +%FT%TZ)" || echo "no changes"
          git push origin "$BRANCH"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: pip install pandas matplotlib

      - name: Make charts
        run: python scripts/make_charts.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: charts_${{ github.run_id }}
          path: |
            data/geth_mid_*.csv
            charts/*.png
          retention-days: 30
